version: '3.4'
services:
  exporter:
    build:
      network: host
      context: .
    container_name: mqtt_exporter
    restart: unless-stopped
    environment:
      - MQTT_CLIENT_ID=exporter
      - MQTT_HOST=
      - MQTT_PORT=1883
      - MQTT_USER=
      - MQTT_PASSWORD=
      - METRICS_PREFIX=mqtt_
      - METRICS_PORT=9101
    volumes:
      - ./:/usr/app/
    expose:
      - 9101
    ports:
      - 9101:9101
